name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - release
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo values"
        run: |
            echo "Hello, World"
            echo ${{ vars.VERCEL_PROJECT_ID }}
            echo ${{ vars.VERCEL_TOKEN }}
            echo ${{ env.VERCEL_TOKEN }}
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ vars.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ vars.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ vars.VERCEL_TOKEN }}
